version: '3.7'

services:
  web:
    build: ./Incopis_Front
    command: uwsgi --socket :8000 --module Incopis_Front.wsgi
    expose: 
      - 8000

    volumes:
      - type: bind 
        source: ./Incopis_Front/static_root/ 
        target: /code/static_root
        read_only: true     

    environment:
      - SQL_USER=incopis
      - SQL_PASSWORD=incopis_password
      - SQL_HOST=db
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=incopis
      - POSTGRES_PASSWORD=incopis_password
      - POSTGRES_DB=incopis_data
    volumes:
      - type: bind 
        source: ./IncopisTestData/data/
        target: /var/lib/postgresql/data/ 
  
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - type: bind 
        source: ./Incopis_Front/static_root/ 
        target: /code/static_root
        read_only: true     

    depends_on:
      - web