# Generated by Django 3.1 on 2020-08-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
