# Generated by Django 3.1.1 on 2020-09-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_manager', '0003_shopper'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='items',
            field=models.ManyToManyField(to='wardrobe_manager.Item'),
        ),
    ]
